# Generated by Django 4.1.1 on 2023-02-18 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Fruits', 'Fruits'), ('Foods', 'Foods'), ('Drinks', 'Drinks')], default='Foods', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrinksCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(choices=[('Soft Drinks', 'Soft Drinks'), ('Drink', 'Drink'), ('Cocktail', 'Cocktail')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('category', models.IntegerField()),
                ('item_details', models.IntegerField()),
                ('order_status', models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=200)),
                ('delivery_location', models.CharField(max_length=700)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='whishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('item_in_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('image', models.CharField(max_length=700)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('image', models.CharField(max_length=700)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.categorie')),
                ('drink_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.drinkscategorie')),
            ],
        ),
        migrations.CreateModel(
            name='CockTail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocktail_name', models.CharField(max_length=200)),
                ('cocktail_image', models.CharField(max_length=500)),
                ('cocktail_description', models.TextField()),
                ('cocktail_price', models.IntegerField()),
                ('cocktail_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.categorie')),
            ],
        ),
    ]
