# Generated by Django 4.1.1 on 2023-02-18 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item_details',
        ),
    ]
