# Generated by Django 4.1.1 on 2023-03-10 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='delivery_location',
        ),
        migrations.RemoveField(
            model_name='ordercheckout',
            name='delivery_location',
        ),
        migrations.RemoveField(
            model_name='ordercheckout',
            name='order_status',
        ),
        migrations.AddField(
            model_name='checkout',
            name='latitide',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='longitude',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='order_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whishlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
