# Generated by Django 4.1.1 on 2023-03-12 23:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_latitide_checkout_latitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='order_placed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
