# Generated by Django 4.1.1 on 2023-02-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whishlist',
            old_name='item_in_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='whishlist',
            old_name='item',
            new_name='item_id',
        ),
    ]
