# Generated by Django 4.1.1 on 2023-02-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_item_in_category_whishlist_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whishlist',
            name='category',
            field=models.IntegerField(),
        ),
    ]
