# Generated by Django 4.1.1 on 2023-03-14 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_checkout_order_placed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='order_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
