# Generated by Django 4.1.1 on 2023-02-26 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_whishlist_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitssCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('Fruits', 'Fruits'), ('Juices', 'Juices')], default='Fruits', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='fruits',
            name='in_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.fruitsscategorie'),
        ),
    ]
