# Generated by Django 4.1.1 on 2023-03-03 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_fruitsscategorie_fruits_in_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricessCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(choices=[('Normal', 'Normal'), ('Advanced', 'Advanced'), ('VIP', 'VIP')], default='Normal', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='fruitsscategorie',
            name='category_name',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Juices', 'Juices'), ('Fruit Salad', 'Fruit Salad')], default='Fruits', max_length=200),
        ),
        migrations.AddField(
            model_name='fruits',
            name='price_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.pricesscategorie'),
        ),
    ]
