# Generated by Django 4.1.1 on 2023-03-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_pricesscategorie_and_more'),
    ]

    operations = [
        migrations.RunSQL('UPDATE django_admin_log SET user_id = (SELECT id FROM web_CustomUser WHERE web_CustomUser.id = django_admin_log.id)')

    ]
